(lang dune 2.7)
(package
 (name yaac)
 (depends
   (dune :build)
   containers
   ppx_subliner
   zarith
   ppx_deriving_yojson
   pringo
   base

  (alcotest :with-test)

 )
  (depopts
    merlin
    utop
    ocamlformat
    ocp-indent
  )
)
