[project]
name = "alife"
version = "0.1"
description = ""
authors = [
    {name = "Mathias Millet", email = "mathias@mmill.eu"},
]
dependencies = [
    "django>=6.0.3",
    "django-click>=2.5.0",
    "django-admin-extra-buttons>=2.1.2",
    "djangorestframework>=3.16.1",
    "django-extensions>=4.1",
    "django-bulma>=0.10.0",
    "setuptools>=82.0.0",
    "typer>=0.24.1",
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "GPLV3"}

[dependency-groups]
dev = [
    "django-types>=0.23.0",
    "ipython>=9.11.0",
    "litecli>=1.17.1",
]